import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { getActiveJobs, type JobRecord } from "./db.js";

const REPO_ROOT = process.cwd();
const DEFAULT_DB_PATH = resolve(REPO_ROOT, "downstream", "data.db");
const DEFAULT_OUT_PATH = resolve(REPO_ROOT, "downstream", "jobs.html");

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "\u0026amp;")
    .replace(/</g, "\u0026lt;")
    .replace(/>/g, "\u0026gt;")
    .replace(/"/g, "\u0026quot;")
    .replace(/'/g, "\u0026#39;");
}

function renderJob(rec: JobRecord): string {
  const title = escapeHtml(rec.job_title ?? "(untitled role)");
  const location = rec.location ? escapeHtml(rec.location) : "";
  const locationType = rec.location_type ? escapeHtml(rec.location_type) : "";
  const applyUrl = escapeHtml(rec.application_url);
  const productUrl = rec.product_page_url ? escapeHtml(rec.product_page_url) : null;

  const locationLine = [location, locationType].filter(Boolean).length > 0
    ? `<div class="location">${[location, locationType].filter(Boolean).map(escapeHtml).join(" · ")}</div>`
    : `<div class="location muted">(location not provided)</div>`;

  return `    <li class="job">
      <a class="job-title" href="${productUrl ?? applyUrl}">${title}</a>
      ${locationLine}
      <a class="job-apply-link" href="${applyUrl}">Apply →</a>
    </li>`;
}

function renderPage(jobs: JobRecord[]): string {
  const items = jobs.map(renderJob).join("\n");
  const count = jobs.length;
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Open Roles — Hiring Signal Tracker</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    :root {
      --bg: #fafaf9; --card: #ffffff; --ink: #18181b; --muted: #71717a;
      --line: #e4e4e7; --hover: #f4f4f5; --accent: #2563eb;
    }
    @media (prefers-color-scheme: dark) {
      :root { --bg:#09090b; --card:#18181b; --ink:#fafafa; --muted:#a1a1aa; --line:#27272a; --hover:#27272a; --accent:#60a5fa; }
    }
    * { box-sizing: border-box; }
    body {
      font: 15px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      background: var(--bg); color: var(--ink); margin: 0; padding: 32px 16px 64px;
    }
    header { max-width: 760px; margin: 0 auto 24px; }
    h1 { font-size: 26px; margin: 0 0 6px; }
    .subtitle { color: var(--muted); font-size: 13px; }
    ul { list-style: none; max-width: 760px; margin: 0 auto; padding: 0; }
    .job {
      background: var(--card); border: 1px solid var(--line); border-radius: 10px;
      padding: 18px 20px; margin-bottom: 12px; transition: background .12s;
      display: grid; grid-template-columns: 1fr auto; grid-template-areas:
        "title title"
        "location apply";
      align-items: center;
    }
    .job:hover { background: var(--hover); }
    .job-title {
      grid-area: title; font-size: 17px; font-weight: 600; color: var(--ink);
      text-decoration: none; margin-bottom: 4px;
    }
    .job-title:hover { color: var(--accent); }
    .location { grid-area: location; color: var(--muted); font-size: 13px; }
    .location.muted { font-style: italic; opacity: .7; }
    .job-apply-link {
      grid-area: apply; background: var(--accent); color: white; padding: 8px 14px;
      border-radius: 6px; text-decoration: none; font-size: 13px; font-weight: 600;
      white-space: nowrap; transition: opacity .12s;
    }
    .job-apply-link:hover { opacity: .88; }
    .empty { text-align: center; color: var(--muted); padding: 64px 0; font-size: 14px; }
    footer { max-width: 760px; margin: 24px auto 0; color: var(--muted); font-size: 12px; }
  </style>
</head>
<body>
  <header>
    <h1>Open Roles</h1>
    <div class="subtitle">${count} ${count === 1 ? "active role" : "active roles"} · auto-generated from validated scrape · data source: <code>jobs.ashbyhq.com/retell-ai</code></div>
  </header>
  <ul>
${items || '    <li class="empty">(no active roles — run <code>npm run orchestrate</code> or <code>npm run downstream:sync</code> to populate)</li>'}
  </ul>
  <footer>
    Generated by <code>npm run jobs:build</code> from <code>downstream/data.db</code> (only <code>is_active = 1</code> rows).
    Regenerate this file after every scrape to keep the list current.
  </footer>
</body>
</html>
`;
}

function main(): void {
  const dbPath = process.argv[2] ? resolve(process.cwd(), process.argv[2]) : DEFAULT_DB_PATH;
  const outPath = process.argv[3] ? resolve(process.cwd(), process.argv[3]) : DEFAULT_OUT_PATH;

  const jobs = getActiveJobs(dbPath);
  const html = renderPage(jobs);
  writeFileSync(outPath, Buffer.from(html, "utf8"));
  console.log(`[jobs:build] wrote ${outPath} (${jobs.length} active ${jobs.length === 1 ? "job" : "jobs"} from ${dbPath})`);
}

main();
